<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>library</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <!-- <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable> -->
    <LangVersion>10.0</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Docs\WorldML.aux" />
    <None Remove="Docs\WorldML.log" />
    <None Remove="Docs\WorldML.out" />
    <None Remove="Docs\WorldML.pdf" />
    <None Remove="Docs\WorldML.synctex.gz" />
    <None Remove="Docs\WorldML.toc" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Glue\" />
    <Folder Include="Properties\" />
    <Folder Include="Tests\" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="LiteNetLib" Version="0.9.7" />
  <PackageReference Include="MongoDB.Bson" Version="2.25.0" />
  <PackageReference Include="System.Text.Json" Version="7.0.2" />
  <!-- <PackageReference Include="NETStandard.Library.Ref" Version="2.1.0" PrivateAssets="All" /> -->
  </ItemGroup>

</Project>
 