<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
    <Folder Include="Tests\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\libs\ObjectIR.net\ObjectIR.net\ObjectIR.net.csproj"
                       OutputItemType="Analyzer"
                      ReferenceOutputAssembly="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="0.9.7" />
  </ItemGroup>

</Project>
 