<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    
    <PackageId>Finite.V12</PackageId>
    <Version>1.0.0</Version>
    <Authors>Charlie-san; Finite</Authors>
    <Description>Finite's V12 game engine powered by CSharp and dreams</Description>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Docs\*.aux" />
    <None Remove="Docs\*.log" />
    <None Remove="Docs\*.out" />
    <None Remove="Docs\*.pdf" />
    <None Remove="Docs\*.synctex.gz" />
    <None Remove="Docs\*.toc" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Templates\Gridspace.xml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Glue\" />
    <Folder Include="Properties\" />
    <Folder Include="Tests\" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="AssimpNetter" Version="6.0.4" />
  <PackageReference Include="LiteNetLib" Version="1.1.0" />
  <PackageReference Include="MongoDB.Bson" Version="2.25.0" />
  <PackageReference Include="BepuPhysics" Version="2.5.0-beta.29" />
  <PackageReference Include="MoonSharp" Version="2.0.0" />
  <PackageReference Include="Serilog" Version="4.4.0" />
  <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contract\Contract.Runtime\Contract.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\Gridspace.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
 